name: Go

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.15', '1.16', '1.17']

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Display Go version
        run: go version

      - name: Install dependencies
        run: go get .

      - name: Unit test
        run: |
          go test -v ./... -covermode=count -coverprofile=coverage.out
          go tool cover -func=coverage.out -o=coverage.out

      - name: Generate cover badge
        run: |
          chmod +x "${GITHUB_WORKSPACE}/.github/build_badge.sh"
          "${GITHUB_WORKSPACE}/.github/build_badge.sh"
          git fetch
          git checkout -b badge 
          git pull
          git merge origin/main --no-edit
          curl "https://img.shields.io/badge/coverage-$total%25-$COLOR" > badge.svg
          git add .
          git commit -m "added badge"
          git push